[versions]
core-database-realm=":core:local_database:realm"
core-di=":core:di"
#Module related to Features:Auth
feature-auth-destination=":features:auth:destination"
feature-auth-components=":features:auth:components"
#Feature:Other features modules
feature-others-destination=":features:others:destination"
feature-others-components=":features:others:components"
#Feature:Facultis
feature-faculty-destination=":features:faculty:destination"
feature-faculty-components=":features:faculty:components"
#feature Admin Office
feature-adminOffice-destination=":features:admin_office:destination"
feature-adminOffice-components=":features:admin_office:components"

#data layers
data-otherInfo=":architecture_layers:data:other_info"
data-departments=":architecture_layers:data:departments"
data-faculties=":architecture_layers:data:faculties"
data-teachers=":architecture_layers:data:teachers"
####
data-admin-offices=":architecture_layers:data:admin_offices"
data-admin-subOffices=":architecture_layers:data:admin_sub_offices"
data-admin-officers=":architecture_layers:data:admin_officers"
#UI layers
common-ui=":architecture_layers:ui:common_ui"
ui-faculties=":architecture_layers:ui:faculties"
ui-teachers=":architecture_layers:ui:teachers"
ui-departments=":architecture_layers:ui:departments"
###
ui-admin-offices=":architecture_layers:ui:admin_offices"
ui-admin-subOffices=":architecture_layers:ui:admin_sub_offices"
ui-admin-officers=":architecture_layers:ui:admin_officers"
#Domain  layers
domain-departments=":architecture_layers:domain:departments"
domain-teachers=":architecture_layers:domain:teachers"
domain-faculties=":architecture_layers:domain:faculties"
###
domain-admin-offices=":architecture_layers:domain:admin_offices"
domain-admin-subOffices=":architecture_layers:domain:admin_sub_offices"
domain-admin-officers=":architecture_layers:domain:admin_officers"


domain-login=":architecture_layers:domain:login"
data-login=":architecture_layers:data:login"
ui-login=":architecture_layers:ui:login"
domain-register=":architecture_layers:domain:register"
data-register=":architecture_layers:data:register"
ui-register=":architecture_layers:ui:register"


domain-departmentInfo=":architecture_layers:domain:department_info"
data-departmentInfo=":architecture_layers:data:department_info"

domain-otherInfo=":architecture_layers:domain:other_info"

ui-otherInfo=":architecture_layers:ui:other_info"

