[versions]
core-database-realm=":core:local_database:realm"
core-di=":core:di"
#Module related to Features:Auth
feature-auth-destination=":features:auth:destination"
feature-auth-components=":features:auth:components"
#
common-ui=":architecture_layers:ui:common_ui"
domain-login=":architecture_layers:domain:login"
data-login=":architecture_layers:data:login"
ui-login=":architecture_layers:ui:login"
domain-register=":architecture_layers:domain:register"
data-register=":architecture_layers:data:register"
ui-register=":architecture_layers:ui:register"
domain-faculties=":architecture_layers:domain:faculties"
data-faculties=":architecture_layers:data:faculties"
ui-faculties=":architecture_layers:ui:faculties"
domain-departments=":architecture_layers:domain:departments"
data-departments=":architecture_layers:data:departments"
ui-departments=":architecture_layers:ui:departments"
domain-departmentInfo=":architecture_layers:domain:department_info"
data-departmentInfo=":architecture_layers:data:department_info"
domain-teachers=":architecture_layers:domain:teachers"
data-teachers=":architecture_layers:data:teachers"
ui-teachers=":architecture_layers:ui:teachers"
domain-otherInfo=":architecture_layers:domain:other_info"
data-otherInfo=":architecture_layers:data:other_info"
ui-otherInfo=":architecture_layers:ui:other_info"
domain-adminOffices=":architecture_layers:domain:admin_offices"
data-adminOffices=":architecture_layers:data:admin_offices"
ui-adminOffices=":architecture_layers:ui:admin_offices"
domain-adminSubOffices=":architecture_layers:domain:admin_sub_offices"
ui-adminSubOffices=":architecture_layers:ui:admin_sub_offices"
data-adminSubOffices=":architecture_layers:data:admin_sub_offices"
domain-adminOfficers=":architecture_layers:domain:admin_officers"
data-adminOfficers=":architecture_layers:data:admin_officers"
ui-adminOfficers=":architecture_layers:ui:admin_officers"
