package com.just.cse.digital_diary.two_zero_two_three.department.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00696B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF59F8FB)
val md_theme_light_onPrimaryContainer = Color(0xFF002020)
val md_theme_light_secondary = Color(0xFF676000)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF6E624)
val md_theme_light_onSecondaryContainer = Color(0xFF1F1C00)
val md_theme_light_tertiary = Color(0xFF6E5E00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFDE264)
val md_theme_light_onTertiaryContainer = Color(0xFF211B00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFCFF)
val md_theme_light_onBackground = Color(0xFF001F2A)
val md_theme_light_surface = Color(0xFFFAFCFF)
val md_theme_light_onSurface = Color(0xFF001F2A)
val md_theme_light_surfaceVariant = Color(0xFFDAE4E4)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4949)
val md_theme_light_outline = Color(0xFF6F7979)
val md_theme_light_inverseOnSurface = Color(0xFFE1F4FF)
val md_theme_light_inverseSurface = Color(0xFF003547)
val md_theme_light_inversePrimary = Color(0xFF2CDBDE)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF00696B)
val md_theme_light_outlineVariant = Color(0xFFBEC8C8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF2CDBDE)
val md_theme_dark_onPrimary = Color(0xFF003738)
val md_theme_dark_primaryContainer = Color(0xFF004F51)
val md_theme_dark_onPrimaryContainer = Color(0xFF59F8FB)
val md_theme_dark_secondary = Color(0xFFD8CA00)
val md_theme_dark_onSecondary = Color(0xFF353100)
val md_theme_dark_secondaryContainer = Color(0xFF4E4800)
val md_theme_dark_onSecondaryContainer = Color(0xFFF6E624)
val md_theme_dark_tertiary = Color(0xFFE0C64C)
val md_theme_dark_onTertiary = Color(0xFF393000)
val md_theme_dark_tertiaryContainer = Color(0xFF534600)
val md_theme_dark_onTertiaryContainer = Color(0xFFFDE264)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F2A)
val md_theme_dark_onBackground = Color(0xFFBFE9FF)
val md_theme_dark_surface = Color(0xFF001F2A)
val md_theme_dark_onSurface = Color(0xFFBFE9FF)
val md_theme_dark_surfaceVariant = Color(0xFF3F4949)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8C8)
val md_theme_dark_outline = Color(0xFF899392)
val md_theme_dark_inverseOnSurface = Color(0xFF001F2A)
val md_theme_dark_inverseSurface = Color(0xFFBFE9FF)
val md_theme_dark_inversePrimary = Color(0xFF00696B)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF2CDBDE)
val md_theme_dark_outlineVariant = Color(0xFF3F4949)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF3CE4E7)
