package com.just.cse.digital_diary.features.faculty.destination.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006685)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBEE9FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F2A)
val md_theme_light_secondary = Color(0xFF006D30)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF99F7A9)
val md_theme_light_onSecondaryContainer = Color(0xFF00210A)
val md_theme_light_tertiary = Color(0xFFBE003C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDADB)
val md_theme_light_onTertiaryContainer = Color(0xFF40000E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFE)
val md_theme_light_onBackground = Color(0xFF191C1E)
val md_theme_light_surface = Color(0xFFFBFCFE)
val md_theme_light_onSurface = Color(0xFF191C1E)
val md_theme_light_surfaceVariant = Color(0xFFDCE4E9)
val md_theme_light_onSurfaceVariant = Color(0xFF40484C)
val md_theme_light_outline = Color(0xFF70787D)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1F3)
val md_theme_light_inverseSurface = Color(0xFF2E3133)
val md_theme_light_inversePrimary = Color(0xFF6AD3FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006685)
val md_theme_light_outlineVariant = Color(0xFFC0C8CD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF6AD3FF)
val md_theme_dark_onPrimary = Color(0xFF003546)
val md_theme_dark_primaryContainer = Color(0xFF004D65)
val md_theme_dark_onPrimaryContainer = Color(0xFFBEE9FF)
val md_theme_dark_secondary = Color(0xFF7EDA8F)
val md_theme_dark_onSecondary = Color(0xFF003916)
val md_theme_dark_secondaryContainer = Color(0xFF005322)
val md_theme_dark_onSecondaryContainer = Color(0xFF99F7A9)
val md_theme_dark_tertiary = Color(0xFFFFB2B8)
val md_theme_dark_onTertiary = Color(0xFF67001D)
val md_theme_dark_tertiaryContainer = Color(0xFF91002C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDADB)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1E)
val md_theme_dark_onBackground = Color(0xFFE1E2E5)
val md_theme_dark_surface = Color(0xFF191C1E)
val md_theme_dark_onSurface = Color(0xFFE1E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF40484C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C8CD)
val md_theme_dark_outline = Color(0xFF8A9297)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val md_theme_dark_inverseSurface = Color(0xFFE1E2E5)
val md_theme_dark_inversePrimary = Color(0xFF006685)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF6AD3FF)
val md_theme_dark_outlineVariant = Color(0xFF40484C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF2596BE)
